dtb-$(CONFIG_MACH_EXYNOS7904_M20LTE_SWA_OPEN) := \
	exynos7870-on7xelte_swa_open_00 \
	exynos7870-on7xelte_swa_open_01 \
	exynos7870-on7xelte_swa_open_02

always            := $(dtb-y) $(dtbo-y)
clean-files       := *.dtb*